title: "Psychophysiological Reactions to Acceleration"
description: "Acceleration vs. Immersion: A study by the MTDML Lab."
baseurl: "psyphy_reakt_acceleration" 
url: "https://martineiribarren.github.io"
theme: jekyll-theme-cayman 
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Configuración de Markdown
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax # Habilita fórmulas matemáticas

# Menú de Navegación
header_pages:
  - index.md
  - pages/theory.md
  - pages/experiment.md
  - pages/metrics.md
  - pages/community.md
  - pages/resources.md
